Paclet[
	Name -> "NeuralNetworks",
Version -> "11.2.127",
MathematicaVersion -> "11.2+",
	Description -> "Neural Network functionality",
	Creator -> "Taliesin Beynon <taliesinb@wolfram.com>, Sebastian Bodenstein <sebastianb@wolfram.com>",
	Loading -> Automatic,
	Extensions -> {
		{"Resource", Root -> "Resources", Resources -> {}},
		{"Kernel", Root -> "Kernel", Context -> {"NeuralNetworks`"}, HiddenImport -> True, Symbols -> {
			"System`NetInitialize",
			"System`NetPort",
			"System`NetPortGradient",
			"System`NetTrain", 
			"System`NetEvaluationMode",
			"System`NetGraph",
			"System`NetChain",
			"System`NetExtract",
			"System`NetReplacePart",
			"System`NetEncoder",
			"System`NetDecoder",
			"System`NetMapOperator",
			"System`NetFoldOperator",
			"System`NetNestOperator",
			"System`NetPairEmbeddingOperator",
			"System`ConstantTimesLayer",
			"System`ConstantPlusLayer",
			"System`ConstantArrayLayer",
			"System`ElementwiseLayer",
			"System`ThreadingLayer",
			"System`BatchNormalizationLayer",
			"System`InstanceNormalizationLayer",
			"System`ConvolutionLayer",
			"System`CrossEntropyLossLayer",
			"System`ResizeLayer",
			"System`AggregationLayer",
			"System`DeconvolutionLayer",
			"System`SpatialTransformationLayer",
			"System`ImageAugmentationLayer",
			"System`DropoutLayer",
			"System`EmbeddingLayer",
			"System`UnitVectorLayer",
			"System`FlattenLayer",
			"System`ReplicateLayer",
			"System`DotPlusLayer",
			"System`LinearLayer",
			"System`DotLayer",
			"System`CatenateLayer",
			"System`MeanSquaredLossLayer",
			"System`MeanAbsoluteLossLayer",
			"System`ContrastiveLossLayer",
			"System`TotalLayer",
			"System`PoolingLayer",
			"System`PaddingLayer",
			"System`ReshapeLayer",
			"System`TransposeLayer",
			"System`SoftmaxLayer",
			"System`SummationLayer",
			"System`PartLayer",
			"System`LocalResponseNormalizationLayer",
			"System`GatedRecurrentLayer",
			"System`BasicRecurrentLayer",
			"System`LongShortTermMemoryLayer",
			"System`SequenceLastLayer",
			"System`SequenceReverseLayer",
			"System`SequenceMostLayer",
			"System`SequenceRestLayer",
			"System`SequenceAttentionLayer",
			"System`NetModel",
			"NeuralNetworks`WLNetExport",
			"NeuralNetworks`WLNetImport",
			"NeuralNetworks`MXNetImport",
			"NeuralNetworks`MXNetExport"
		}}
	}
]
